### ISSUE TITLE
hruby-0.3.1's Cabal file does not declare a dependency on Ruby

### ISSUE THREAD

**Issue by peti** [bartavelle/hruby#10]
The Cabal file for this package should declare `Includes:  "ruby.h"` and appropriate `Extra-Libraries: ...` stanzas because the build fails if those resources aren't available.

**Comment by bartavelle** [comment]
`ruby.h` comes from your host ruby install, it's doesn't ship with the package. The custom `Setup.hs` tries to find it, but you'll have to give it all the pathes explicitly with nix. By the way, if you manage to, could you send me an updated version of this :

https://github.com/bartavelle/hruby/blob/22785b8bca9c6bd518c2d9dcc42898c9a8feeea4/Setup.hs#L72

Because it actually doesn't work with ruby1.9 ...

**Comment by bartavelle** [comment]
Also I used to have build flags and several sets of `Extra-Libraries` but it was just too brittle, as all distributions seem to behave differently with regards to how they install one of the ruby versions.

**Comment by peti** [comment]
> `ruby.h` comes from your host ruby install, it's doesn't ship with the package.

I know. What I wonder is why you don't declare the dependency on the header in your Cabal file?

**Comment by bartavelle** [comment]
Because it can have many names and many locations. Earlier versions did that : https://github.com/bartavelle/hruby/blob/v0.2.0/hruby.cabal#L46-L56 but this just doesn't work.

**Comment by bartavelle** [comment]
Ah, I am not familiar with the `Include` pragma. I also think it wouldn't work because it's generally not in the standard include pathes.

**Comment by peti** [comment]
You are not supposed to hard-code random search paths in your Cabal file. It's the users task to provide a working build environment that contains all the resources your build needs. It's your task, though, to declare the resources that your build needs so that the user has a chance to provide them! In other words, you should add `includes: <ruby.h>`, because you package won't compile without that header, but you should *not* try to guess the system location of that file. Instead, let the user tell your build how to find it by passing appropriate `--extra-include-dirs` and `--extra-lib-dirs` flags.

**Comment by bartavelle** [comment]
Hum that sounds much more reasonable than what I did ... I guess I'll have to fix all my contrived logic :/

There is still the issue with the library name, but this can probably be handled by build flags.

**Comment by bartavelle** [comment]
OTOH the current solutions should autodetect all search pathes automatically ...

**Comment by bartavelle** [comment]
Added with c9e846e

**Comment by bartavelle** [comment]
I added the relevant flag, but did not change the setup logic, as it's really helpful when you are building packages that depend on `hruby`. Is that blocking for your use case ?

**Comment by peti** [comment]
Yes, the dependency declaration is still incomplete. This change alone doesn't help us much in Nix.

**Comment by bartavelle** [comment]
I don't know how to fix it ... what would you need ? I really wish to keep the current behaviour (ie. you can install `language-puppet` without worrying about how `hruby` finds its ruby) though.

**Comment by peti** [comment]
Why would declaring the link-time dependency on `ruby` disturb the build in any way? I don't see how *omitting* this information could possibly bring any advantages.

**Comment by bartavelle** [comment]
Because the library can be called `libruby`, `libruby20`, `libruby21`, etc ...

**Comment by bartavelle** [comment]
It's `libruby1.8` on the computer I am currently using.

**Comment by bartavelle** [comment]
Also it's not in the cabal file, but it's in the cabal configuration. It's just that it can't be a static value, so it's computed by `Setup.hs`.

**Comment by peti** [comment]
Does Cabal not auto-detect the proper configuration if you add flags for the various alternative library names (like you did in https://github.com/bartavelle/hruby/blob/v0.2.0/hruby.cabal#L46-L56 but minus the hard-coded search paths)?

**Comment by bartavelle** [comment]
No it only works for haskell dependencies ...

**Comment by peti** [comment]
Duh, that sucks. :disappointed: Then there's probably no way to remedy this issue properly.

**Comment by bartavelle** [comment]
Why is it important that the library name is in the cabal file ? I can add a dummy name, as I suppose `Setup.hs` can be coerced into ignoring it.

**Comment by peti** [comment]
We generate build recipes for NixOS automatically from the Cabal file, i.e.:

    mkDerivation {
      pname = "hruby";
      version = "0.3.1.1";
      buildDepends = [
        aeson attoparsec base bytestring scientific stm text
        unordered-containers vector
      ];
      testDepends = [ aeson attoparsec base QuickCheck text vector ];
      description = "Embed a Ruby intepreter in your Haskell program !";
      license = stdenv.lib.licenses.bsd3;
    }

That recipe *should* contain an entry `extraLibraries = [ruby]`, because without that information `ruby` won't be available during the build. Since the Cabal file never mentions that dependency, however, our generator script cannot know about it; thus the build in NixOS fails.

We can work around this within NixOS by adding an appropriate configuration entry manually, but obviously we'd prefer to have correct recipes generated automatically.

**Comment by bartavelle** [comment]
I'll try to see if I can override it with my custom `Setup.hs` this week.

**Comment by peti** [comment]
If you can figure out such a solution quickly, then I am all for it. However, please don't invest much more time and effort into this subject than you already did. I've accepted the fact that Cabal is insufficient in that area, that there's no real good solution for this issue, and that we -- the Nixpkgs maintainers -- have to live with having to configure a manual override (what we already did in https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-common.nix#L25-26) to help our package generation tools.

**Comment by bartavelle** [comment]
Took me 10 seconds, pushed with e762f36 . Do you need a proper cabal release for this to work ?

**Comment by peti** [comment]
Very cool, thank you! Yes, a new release to Hackage would be great.

**Comment by bartavelle** [comment]
Done !

**Comment by peti** [comment]
Thank you! Everything is fine now: http://hydra.cryp.to/build/785867

**Comment by bartavelle** [comment]
Does that mean there is also an automated `language-puppet` build ?

**Comment by peti** [comment]
Just follow the "NixOS" link on the respective package's Hackage page; these links point to our Continuous Integration System. In case of `language-puppet`, http://hackage.haskell.org/package/language-puppet points to http://hydra.nixos.org/job/nixpkgs/haskell-updates/haskellngPackages.language-puppet.x86_64-linux, which is currently still marked *broken*, because `hruby` used to fail. The build should update shortly.

**Comment by peti** [comment]
I just tried to build it and opened a new tickets with the issues I've encountered.

**Comment by bartavelle** [comment]
Thanks !
