### ISSUE TITLE
Add hruby to stackage

### ISSUE THREAD

**Issue by PierreR** [bartavelle/hruby#16]
Now that stackage built with Ubuntu 16.04, it would be nice try to have it available there.

**Comment by bartavelle** [comment]
I don't think it would be ever accepted, because of the ruby dev dependencies ...

**Comment by PierreR** [comment]
It would (see linked issue)
;-)

**Comment by bartavelle** [comment]
Let's do this then!

**Comment by bartavelle** [comment]
It seems to work, should be up in next nightly. I also updated language-puppet dependencies.

**Comment by PierreR** [comment]
Oh waow I was about to try the update of `servant` in language-puppet and I have just seen that you beat me to it. Awesome.

**Comment by bartavelle** [comment]
Well, I haven't tested anything but `stack test` ...

**Comment by PierreR** [comment]
I haven't tested it with ghc-8 yet but so far everything is still working as expected with ghc-7.10.3.
