### ISSUE TITLE
Support for ruby-2.4.0?

### ISSUE THREAD

**Issue by peti** [bartavelle/hruby#21]
Does this library support ruby 2.4.x correctly?

I'm wondering because I managed to compile it, but none of the builds that depend on `hruby`, like `language-puppet`, link successfully with that resulting package, i.e.  I get errors like these ones:

~~~
[  395s] /usr/lib64/ghc-8.0.2/hruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS/libHShruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS.a(Bindings.o):(.text+0x253d): more undefined references to `rb_str_new2' follow
[  395s] /usr/lib64/ghc-8.0.2/hruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS/libHShruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS.a(Bindings.o):(.text+0x27bd): undefined reference to `rb_ary_new2'
[  395s] /usr/lib64/ghc-8.0.2/hruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS/libHShruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS.a(Bindings.o):(.text+0x29ab): undefined reference to `rb_ary_new4'
[  395s] /usr/lib64/ghc-8.0.2/hruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS/libHShruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS.a(Helpers.o):(.text+0x478f): undefined reference to `rb_ary_new4'
[  395s] /usr/lib64/ghc-8.0.2/hruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS/libHShruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS.a(Helpers.o):(.text+0x4d5a): undefined reference to `rb_str_new2'
[  395s] /usr/lib64/ghc-8.0.2/hruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS/libHShruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS.a(Helpers.o):(.text+0x5872): undefined reference to `rb_str_new2'
[  395s] /usr/lib64/ghc-8.0.2/hruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS/libHShruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS.a(Helpers.o):(.text+0x621a): undefined reference to `rb_str_new2'
[  395s] /usr/lib64/ghc-8.0.2/hruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS/libHShruby-0.3.4.3-8m7CsJorZf257hqkjk3RnS.a(Helpers.o):(.text+0x656e): undefined reference to `rb_str_new2'
[  395s] collect2: error: ld returned 1 exit status
~~~

**Comment by bartavelle** [comment]
I never tested it with ruby 2.4.x, so it is no wonder it doesn't work. I don't think GHC checks that anything links when compiling a library, so it is not strange either.

I will try to take a look at this, but I do not even know if it will work. Ruby is horrible to embed, and some versions will not even run alongside GHC. Documentation is inexistent too, so it will be reading the include files again :(

**Comment by bartavelle** [comment]
What distribution do you use with ruby 2.4 by the way ?

**Comment by peti** [comment]
I've been running those tests on openSUSE Tumbleweed. I built `hruby` with ruby 2.2.x until now, but support for that version has been discontinued a few days ago.

**Comment by bartavelle** [comment]
I installed thumbleweed, but it ships with ruby 2.2. After installing `ruby2.4-devel`, I can't find a way to make it the default through `update-alternative`. Removing 2.2 seems to trash yast and other things with it. How did you set your system up?

**Comment by bartavelle** [comment]
With this change in Setup.hs, I could compile and link properly:

```
diff --git a/Setup.hs b/Setup.hs
index fcbb77b..636f238 100644
--- a/Setup.hs
+++ b/Setup.hs
@@ -32,7 +32,7 @@ evalRuby :: String            -- expression to evaluate
 evalRuby exp = do
     let getruby [] = return (ExitFailure 3, "beuh", undefined)
         getruby (x:xs) = readProcessWithExitCode x ["-e", exp] "" `catch` \ (_ :: IOException) -> getruby xs
-    (exitCode, out, err) <- getruby [ "ruby2.1", "ruby2.0", "ruby2", "ruby1.8", "ruby"]
+    (exitCode, out, err) <- getruby [ "ruby.ruby2.4", "ruby2.1", "ruby2.0", "ruby2", "ruby1.8", "ruby"]
     return $ if exitCode == ExitSuccess
                then Just out
                else Nothing

```

**Comment by peti** [comment]
> With this change in Setup.hs, I could compile and link properly ...

I can compile and link `hruby` successfully, too, but the resulting library doesn't actually work. Did you manage to build any package that depends on `hruby` successfully, too, like `language-puppet`?

> I installed thumbleweed, but it ships with ruby 2.2.

The change that removes ruby 2.2 is not public yet; it's currently just in staging so that people have an opportunity to fix failing builds before it's released. 

It should be possible to compile `hruby` with ruby 2.4 on Tumbleweed these days by configuring it with the flags `--extra-include-dir=/usr/include/ruby-2.4.0 --extra-include-dir=/usr/include/ruby-2.4.0/x86_64-linux-gnu --configure-option="--rubyversion=24 --rubylib=ruby2.4"`. Generally speaking, I don't believe that the issues I was having are in any way related to openSUSE, specifically. I'm pretty sure they would occur in any build environment that uses ruby 2.4.

**Comment by bartavelle** [comment]
I just used `cabal test` to verify it linked. However, I suspect it might not exercise all imports! I will try again later, with `language-puppet`.

**Comment by bartavelle** [comment]
(And yes, I agree these issues should not be SuSE specific)

**Comment by bartavelle** [comment]
I could run `language-puppet` too! Can you tell me what the output of the hruby setup is for you? For me it is:

    Detected ruby: RubyInfo {rbVersion = (2,4,1), rbInstallName = "ruby.ruby2.4", rbIncludes = ["/usr/include/ruby-2.4.0","/usr/include/ruby-2.4.0/x86_64-linux-gnu","/usr/lib64/ruby/2.4.0/x86_64-linux-gnu"], rbLib = "/usr/lib64", rbLibName = "ruby2.4"} cc:["-DRUBY2","-DRUBY21"]


also:

```
ldd .stack-work/install/x86_64-linux-tinfo6/lts-8.23/8.0.2/bin/puppetresources 
	linux-vdso.so.1 (0x00007ffedd7ec000)
	libruby2.4.so.2.4 => /usr/lib64/libruby2.4.so.2.4 (0x00007ffbe0396000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007ffbe000e000)
	libz.so.1 => /lib64/libz.so.1 (0x00007ffbdfdf7000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ffbdfbef000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007ffbdf9ec000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ffbdf7e6000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffbdf5c8000)
	libgmp.so.10 => /usr/lib64/libgmp.so.10 (0x00007ffbdf335000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ffbdf023000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ffbdee0c000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ffbdea66000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007ffbde829000)
	/lib64/ld-linux-x86-64.so.2 (0x00005646fdce3000)
```

**Comment by bartavelle** [comment]
(I also verified it worked)

**Comment by bartavelle** [comment]
I pushed a change that auto-detects ruby2.4 for opensuse. It would be nice if you could test it too.

**Comment by peti** [comment]
I applied ab6e3492ad1db9aa1236e2b61738cd63a69996ce to our build. The results are visible at <https://build.opensuse.org/package/show/devel:languages:haskell:lts:8/ghc-hruby> and https://build.opensuse.org/build/devel:languages:haskell:lts:8/openSUSE_Tumbleweed/x86_64/ghc-hruby/_log has the complete build log for Tumbleweed. The line you were interested in reads:

    Detected ruby: RubyInfo {rbVersion = (2,4,1), rbInstallName = "ruby.ruby2.4", rbIncludes = ["/usr/include/ruby-2.4.0","/usr/include/ruby-2.4.0/x86_64-linux-gnu","/usr/lib64/ruby/2.4.0/x86_64-linux-gnu"], rbLib = "/usr/lib64", rbLibName = "ruby2.4"} cc:["-DRUBY2","-DRUBY21"]

Now, this patch creates a working library, indeed, language-puppet now compiles again, too: <https://build.opensuse.org/package/show/devel:languages:haskell:lts:8/ghc-language-puppet>.

**Comment by bartavelle** [comment]
Is that fixed for you if I push a new version to cabal?

**Comment by peti** [comment]
You mean to Hackage? Yes, a new Hackage release would be very welcome!

**Comment by bartavelle** [comment]
done, version 0.3.4.4

**Comment by peti** [comment]
Thank you very much for the quick fix!
