### ISSUE TITLE
hruby-0.3.1 tests fail because of missing file

### ISSUE THREAD

**Issue by peti** [bartavelle/hruby#9]
We're getting the following error in NixOS:

    Running 1 test suites...
    Test suite test-roundtrip: RUNNING...
    test-roundtrip: Stack "Could not load ./test/test.rb" "cannot load such file -- ./test/test.rb\n"
    Test suite test-roundtrip: FAIL

Is it possible that this file is missing from the release archive on Hackage?

**Comment by bartavelle** [comment]
Good catch ! I commited a fix (22785b8) and will push to hackage as soon as possible.

**Comment by bartavelle** [comment]
Version 0.3.1.1 should have the required test files.
